//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.19 at 10:29:18 AM EST 
//


package com.revature.models;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for superPower.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="superPower">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Flight"/>
 *     &lt;enumeration value="Gravity"/>
 *     &lt;enumeration value="Invisibility"/>
 *     &lt;enumeration value="Invulnerability"/>
 *     &lt;enumeration value="Pyrokinesis"/>
 *     &lt;enumeration value="Teleportation"/>
 *     &lt;enumeration value="SuperSpeed"/>
 *     &lt;enumeration value="ChronoGenesis"/>
 *     &lt;enumeration value="LaserEyes"/>
 *     &lt;enumeration value="FutureSight"/>
 *     &lt;enumeration value="SuperStrength"/>
 *     &lt;enumeration value="Telekinesis"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "superPower")
@XmlEnum
public enum SuperPower {

    @XmlEnumValue("Flight")
    FLIGHT("Flight"),
    @XmlEnumValue("Gravity")
    GRAVITY("Gravity"),
    @XmlEnumValue("Invisibility")
    INVISIBILITY("Invisibility"),
    @XmlEnumValue("Invulnerability")
    INVULNERABILITY("Invulnerability"),
    @XmlEnumValue("Pyrokinesis")
    PYROKINESIS("Pyrokinesis"),
    @XmlEnumValue("Teleportation")
    TELEPORTATION("Teleportation"),
    @XmlEnumValue("SuperSpeed")
    SUPER_SPEED("SuperSpeed"),
    @XmlEnumValue("ChronoGenesis")
    CHRONO_GENESIS("ChronoGenesis"),
    @XmlEnumValue("LaserEyes")
    LASER_EYES("LaserEyes"),
    @XmlEnumValue("FutureSight")
    FUTURE_SIGHT("FutureSight"),
    @XmlEnumValue("SuperStrength")
    SUPER_STRENGTH("SuperStrength"),
    @XmlEnumValue("Telekinesis")
    TELEKINESIS("Telekinesis");
    private final String value;

    SuperPower(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SuperPower fromValue(String v) {
        for (SuperPower c: SuperPower.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
