//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.19 at 10:29:18 AM EST 
//


package com.revature.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SuperHero complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SuperHero">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="superPower" type="{http://www.example.org/SuperHero}superPower"/>
 *         &lt;element name="weakness" type="{http://www.example.org/SuperHero}superPower"/>
 *         &lt;element name="powerLevel" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SuperHero", propOrder = {
    "name",
    "superPower",
    "weakness",
    "powerLevel"
})
public class SuperHero {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected SuperPower superPower;
    @XmlElement(required = true)
    protected SuperPower weakness;
    protected int powerLevel;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the superPower property.
     * 
     * @return
     *     possible object is
     *     {@link SuperPower }
     *     
     */
    public SuperPower getSuperPower() {
        return superPower;
    }

    /**
     * Sets the value of the superPower property.
     * 
     * @param value
     *     allowed object is
     *     {@link SuperPower }
     *     
     */
    public void setSuperPower(SuperPower value) {
        this.superPower = value;
    }

    /**
     * Gets the value of the weakness property.
     * 
     * @return
     *     possible object is
     *     {@link SuperPower }
     *     
     */
    public SuperPower getWeakness() {
        return weakness;
    }

    /**
     * Sets the value of the weakness property.
     * 
     * @param value
     *     allowed object is
     *     {@link SuperPower }
     *     
     */
    public void setWeakness(SuperPower value) {
        this.weakness = value;
    }

    /**
     * Gets the value of the powerLevel property.
     * 
     */
    public int getPowerLevel() {
        return powerLevel;
    }

    /**
     * Sets the value of the powerLevel property.
     * 
     */
    public void setPowerLevel(int value) {
        this.powerLevel = value;
    }

}
